name: Rust

on:
  push:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --target x86_64-pc-windows-gnu
        
  release:
  if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    uses: softprops/action-gh-release@v1
    with:
      files: 
      - target/release/fenestra.exe
