name: Rust

on:
  push:
    tags: [ "v*" ]
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --target x86_64-pc-windows-gnu
    - if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/fenestra.exe
